dat=read.table(file="Downloads//2014-04-24_CRISPR_KO_screen/CRISPR_r1r2_genes.tab",sep="\t",header=T)
foldchange=(dat[,2]+dat[,3])/(dat[,6]+dat[,7])
x=seq(1:500000)

png(file="R1R2_genes.png")
plot(log((dat[,2]+dat[,3])),log((dat[,6]+dat[,7])),xlab="R1",ylab="R2")
lines(log(x),log(x))
lines(log(x),log(x/2),col="green")
lines(log(x),log(x*2),col="green")
lines(log(x),log(x/4),col="red")
lines(log(x),log(x*4),col="red")
dev.off()

dat=read.table(file="Downloads//2014-04-24_CRISPR_KO_screen/CRISPR_r1r3_genes.tab",sep="\t",header=T)
foldchange=(dat[,2]+dat[,3])/(dat[,6]+dat[,7])
x=seq(1:500000)

png(file="R1R3_genes.png")
plot(log((dat[,2]+dat[,3])),log((dat[,6]+dat[,7])),xlab="R1",ylab="R2")
lines(log(x),log(x))
lines(log(x),log(x/2),col="green")
lines(log(x),log(x*2),col="green")
lines(log(x),log(x/4),col="red")
lines(log(x),log(x*4),col="red")
dev.off()

dat=read.table(file="Downloads//2014-04-24_CRISPR_KO_screen/CRISPR_r2r3_genes.tab",sep="\t",header=T)
foldchange=(dat[,2]+dat[,3])/(dat[,6]+dat[,7])
x=seq(1:500000)

png(file="R2R3_genes.png")
plot(log((dat[,2]+dat[,3])),log((dat[,6]+dat[,7])),xlab="R1",ylab="R2")
lines(log(x),log(x))
lines(log(x),log(x/2),col="green")
lines(log(x),log(x*2),col="green")
lines(log(x),log(x/4),col="red")
lines(log(x),log(x*4),col="red")
dev.off()