#!/usr/bin/perl
use strict;
use warnings;
my $file         = shift; # get the file name, somehow
open INFILE ,$file;
$file=~/(.*)\.+/;
my $filebase=$1;
open NORMAL , ">".$filebase."_3prime.fastq";
open REVERSE , ">".$filebase."_5prime.fastq";
open OTHER , ">".$filebase."_other.fastq";
my $id="";
my $score="";
my $seq="";
my $now_comes_score=0;
my $seq_read_in=0;
my $threeprimcount=0;
my $fiveprimcount=0;
my $shitcount=0;
my $left="";
my $right="";
my $start=0;
my $end=0;
LOOP: foreach my $line (<INFILE>){
    chomp $line;
    if($line=~m/^@(M0110.*)/){
	$id=$1;
	$seq_read_in=0;
    }elsif($line=~m/^\+$/){
	$now_comes_score=1;
    }elsif($now_comes_score==0){
	$seq=$line;
    }elsif($now_comes_score==1){
	$score=$line;
	$now_comes_score=0;
	$seq_read_in=1;
    }
    if($seq_read_in==1 && $seq=~m/(.*)CGTCAATTTT.+TTAA(.*)/){
	$left=$1;$right=$2;
	if(length($left)>=5 || length($right) >=5){
	if(length($left)>length($right)){
	    $seq=$left;
	    $start=$-[1];
	    $end=$+[1];
	    $score=substr($score,$start,$end);
	    print REVERSE"\@$id\n$seq\n\+\n$score\n";
	    next LOOP;
	}else{
	    $seq=$right;
	    $start=$-[2];
	    $end=$+[2];
	    $score=substr($score,$start,$end);
	    print NORMAL "\@$id\n$seq\n\+\n$score\n";
	    next LOOP;
	}
	}
	$threeprimcount++;
	
    }elsif($seq_read_in==1 && $seq=~m/(.*)GTACGTCACAAT.+TTAA(.*)/){
	$left=$1;$right=$2;
	if(length($left)>=5 || length($right) >=5){
	if(length($left)>length($right)){
	    $seq=$left;
	    $start=$-[1];
	    $end=$+[1];
	    $score=substr($score,$start,$end);
	    print NORMAL "\@$id\n$seq\n\+\n$score\n";
	    next LOOP;
	}else{
	    $seq=$right;
	    $start=$-[2];
	    $end=$+[2];
	    $score=substr($score,$start,$end);
	    print REVERSE "\@$id\n$seq\n\+\n$score\n";
	    next LOOP;
	}
	}
	$fiveprimcount++;
	$score=substr($score,$start,$end);
    }elsif($seq_read_in==1){
	print OTHER "\@$id\n$seq\n\+\n$score\n";
	$shitcount++;
	next LOOP;
    }
}
close INFILE;
close NORMAL;
close REVERSE;
close OTHER;
